module.exports = Object.freeze ({
    ROLE_PATIENT: 1,
    ROLE_DOCTOR: 2,
    ROLE_STAFF: 3,
    DELETED_ENTITY: 1,
    NOT_DELETED_ENTITY: 0,
    FIRST_RATTING: 2.5,
    STATUS_CONVERSATION_TALKING: 1,
    STATUS_CONVERSATION_FINISH:2
});