module.exports = Object.freeze({
    ROLE_PATIENT: 1,
    ROLE_DOCTOR: 2,
    ROLE_STAFF: 3,
    DELETED_ENTITY: 1,
    NOT_DELETED_ENTITY: 0,
    FIRST_RATTING: 2.5,
    STATUS_CONVERSATION_TALKING: 1,
    STATUS_CONVERSATION_FINISH: 2,
    RECORD_CHAT_STRING: 1,
    RECORD_CHAT_IMAGE: 2,
    CHAT_HISTORY_EXIST: 1,
    CHAT_HISTORY_PATIENT_DELETE: 2,
    CHAT_HISTORY_DOCTOR_DELETE: 3,
    PERCENT_PAY_FOR_DOCTOR: 0.8
});